[package]
name = "blink"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
directories = "5.0"
toml = "0.8"
open = "5.3.2"
